
// This file was auto-generated by ML.NET Model Builder. 

using HelloMLNETConsoleApp;

// Create single instance of sample data from first line of dataset for model input
IrisModel.ModelInput sampleData = new IrisModel.ModelInput()
{
    Sepal_length = 48F,
    Sepal_width = 34F,
    Petal_length = 16F,
    Petal_width = 2F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual __Label with predicted __Label from sample data...\n\n");


Console.WriteLine($"__Label: {0F}");
Console.WriteLine($"Sepal_length: {48F}");
Console.WriteLine($"Sepal_width: {34F}");
Console.WriteLine($"Petal_length: {16F}");
Console.WriteLine($"Petal_width: {2F}");


var sortedScoresWithLabel = IrisModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

