
// This file was auto-generated by ML.NET Model Builder. 

using AnalisisSentimenConsoleApp;

// Create single instance of sample data from first line of dataset for model input
AnalisisSentimen.ModelInput sampleData = new AnalisisSentimen.ModelInput()
{
    Text = @"Film king Arthur ini film paling jelek dari seluruh cerita King Arthur",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Class_label with predicted Class_label from sample data...\n\n");


Console.WriteLine($"Class_label: {0F}");
Console.WriteLine($"Text: {@"Film king Arthur ini film paling jelek dari seluruh cerita King Arthur"}");


var sortedScoresWithLabel = AnalisisSentimen.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

